name: Fetch Top News Stories

on:
  schedule:
    # Run this workflow every day at 11 PM UTC
    - cron:  '0 23 * * *'

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install newsapi-python

    - name: Run script
      run: python fetch_news.py
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Log today's top news stories" -a
        git push
